# Site settings
title: ESA Stack
email: esa.stack@oppo.com
url: &url https://esastack.github.io
github: &github https://github.com/esastack
description: "Elastic Service Architecture"
keywords: "Micro-Services, Service Mesh, Framework, Java"
skills: "Elastic Service Architecture"
meta_author: ESA Stack

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 807e9e #80B3FF
  primary-rgb: "128,126,158" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: OPPO ESA Stack Project
  location: Location
  social: Around the Web
  credits: Contributing

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: *github

# Postal address (add as many lines as necessary)
address:
  - line: China - ShenZhen
  - line: China - ChengDu
  - line: ...

# Credits content
credits: "Hi there! We're thrilled that you'd like to contribute to this project. Your help is essential for keeping it great."

# Build settings
markdown: kramdown
permalink: pretty

projects:
  - name: ESA Restlight
    baseUrl: *url
    path: esa-restlight
    github: https://github.com/esastack/esa-restlight
    description: ESA Restlight is a lightweight and rest-oriented web framework.
  - name: ESA HttpClient
    baseUrl: *url
    path: esa-httpclient
    github: https://github.com/esastack/esa-httpclient
    description: ESA Restlight is a lightweight and rest-oriented web framework.
  - name: ESA HttpServer
    baseUrl: https://github.com
    path: esastack/esa-httpserver
    github: https://github.com/esastack/esa-httpserver
    description: ESA HttpServer is an asynchronous event-driven HTTP server based on netty.
  - name: ESA Commons
    baseUrl: https://github.com
    path: esastack/esa-commons
    github: https://github.com/esastack/esa-commons
    description: ESA Commons is the common lib of ESA Stack.